source 'https://rubygems.org'
#ruby '>=2'

gem 'rspec'
gem 'oauth2'
gem 'dig_rb'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-reloader'
gem 'sinatra-xsendfile'
gem 'sinatra-activerecord'
gem 'activerecord', '~> 4.2.0'
gem 'erubis'
gem 'rake'
gem 'rack-test'
gem 'resque'
gem 'resque-status'
gem 'thin'
gem 'mysql2', '0.4.10'
gem 'unidecode'
gem 'rack-proxy'
gem 'rack-rewrite'
gem 'inifile'
gem 'fuzzy-string-match'
gem 'musicbrainz'
gem 'tiny_tds'
gem 'rest-client'
