source 'https://rubygems.org'
#ruby '>=2'

gem 'rspec'
gem 'oauth2'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-reloader'
gem 'sinatra-xsendfile'
gem 'erubis'
gem 'rake'
gem 'resque'
gem 'resque-status'
gem 'thin'
gem 'mysql2'

gem 'musicbrainz'
gem 'tiny_tds'
